# netlify.toml configuration file for Dr. P.I. Skosana Dental Care website

# Global build settings
[build]
  # Directory to publish (the root directory in this case)
  publish = "."
  
  # No build command needed for this static site
  command = ""

# Redirects and rewrites
[[redirects]]
  # Redirect all paths to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  
  # Don't redirect actual files
  force = false

# Headers for security and caching
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache control for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Environment variables (if needed)
[build.environment]
  NODE_VERSION = "16"
